workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        # اگر نیازی به Expo token نداری، این بخش خالی بماند
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Prebuild Expo
        script: npx expo prebuild
      - name: Build APK
        script: cd android && gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
